# Generated by Django 4.2.3 on 2023-07-26 23:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('moveset', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name=64), size=4)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
