# Generated by Django 4.2.3 on 2023-07-27 00:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_pokemon_moveset'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moveset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=4),
        ),
    ]
