# Generated by Django 4.2.3 on 2023-07-27 22:15

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pokemon_moveset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='moveset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=str, max_length=64), default=list, size=4),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=100)),
                ('exp_points', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
        ),
    ]
