# Generated by Django 4.2.3 on 2023-07-28 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_pokemon_moveset_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
