# Generated by Django 4.2.3 on 2023-07-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_training_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=128)),
                ('pokemon', models.ManyToManyField(to='main_app.pokemon')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_app.pokemon')),
            ],
        ),
    ]
