# Generated by Django 4.2.3 on 2023-07-29 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_training_options_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
